{{- if .Values.prometheus.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  metrics:
    - name: success-share
      interval: 1m
      successCondition: len(result) == 0 || result[0] >= 0.99
      failureLimit: 0
      provider:
        prometheus:
          address: {{ .Values.prometheus.address }}
          query: |
            sum(rate(
              fpi_http_requests_total{service="{{ .Release.Name }}-canary", success="true"}[1m])
            ) by (service)
            /
            sum(rate(
              fpi_http_requests_total{service="{{ .Release.Name }}-canary"}[1m])
            ) by (service)
            unless sum(rate(
              fpi_http_requests_total{service="{{ .Release.Name }}-canary"}[1m])
            ) by (service) == 0
{{- end }}