{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fpi.fullname" . }}-service-monitor
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ include "fpi.name" . }}
spec:
  selector:
    matchLabels:
      {{- include "fpi.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}